# Generated by Django 6.0.6 on 2026-06-07 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('keywords', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrendSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter'), ('youtube', 'YouTube'), ('combined', 'Combined')], max_length=20)),
                ('summary_text', models.TextField()),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral'), ('mixed', 'Mixed')], default='neutral', max_length=20)),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('key_themes', models.JSONField(default=list)),
                ('trending_keywords', models.JSONField(default=list)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('data_points_count', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='analytics.topic')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='TweetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField()),
                ('author_id', models.CharField(max_length=100)),
                ('retweet_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('reply_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='analytics.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100, unique=True)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('channel_title', models.CharField(max_length=200)),
                ('view_count', models.BigIntegerField(default=0)),
                ('like_count', models.BigIntegerField(default=0)),
                ('comment_count', models.BigIntegerField(default=0)),
                ('published_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='analytics.topic')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='EngagementMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('total_posts', models.IntegerField(default=0)),
                ('total_likes', models.BigIntegerField(default=0)),
                ('total_shares', models.BigIntegerField(default=0)),
                ('total_comments', models.BigIntegerField(default=0)),
                ('avg_engagement', models.FloatField(default=0.0)),
                ('sentiment_positive', models.FloatField(default=0.0)),
                ('sentiment_negative', models.FloatField(default=0.0)),
                ('sentiment_neutral', models.FloatField(default=0.0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='analytics.topic')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('topic', 'platform', 'date')},
            },
        ),
    ]
