# Generated by Django 6.0.6 on 2026-06-07 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alert_type', models.CharField(choices=[('sentiment_drop', 'Sentiment Drop'), ('engagement_spike', 'Engagement Spike'), ('volume_spike', 'Volume Spike'), ('keyword_mention', 'Keyword Mention')], max_length=30)),
                ('threshold', models.FloatField(help_text='Threshold value that triggers the alert')),
                ('email', models.EmailField(blank=True, help_text='Email for notifications', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='analytics.topic')),
            ],
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_value', models.FloatField()),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='alerts.alert')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
    ]
